### ISSUE TITLE
Enable to kick out co-author from the current mob

### ISSUE THREAD

**Issue by niksumeiko** [rkotze/git-mob#130]
## Summary

Provide an option to kick out one/many co-authors you currently mob with. 

```shell
# Started together
git mob ab hi jd

# Did some work, committed together
git commit -m "X"

# Then `jd` had to leave
# We want to kick out the `jd` and continue with the rest
git mob -jd
```
_(notice the `-` hyphen before the initials)_

## Motivation

- Easy to kick out particular co-authors but keep others in your mob

## Describe alternatives you've considered

Currently, I am doing this by switching to solo mode and then re-adding all co-authors who continue the mob with me.

```shell
git mob ab hi jd
git commit -m "X"
git solo
git mob ab hi
```

## Additional context

- Implementing it via a trailing hyphen before the initials will make it super easy to remember how to use the command.
- When the excluded initials are not presented in the current mob, the command could output an error message:
```shell
$ git mob -jd
Mob error: John Doe is not in the current mob. No one got kicked out.
```
- Or when the excluded initials don't match any existing co-author:
```shell
$ git mob -jd -ph
Mob error: Author with initials "ph" not found!
```
- The term "kick out" could be replaced with "exclude"
(e.g., ~kick out~ exclude co-author)

**Comment by rkotze** [comment]
Hi @niksumeiko 

Thanks for your suggestion and listing the current commands you are using.

When changing co-authors you don't need to run solo. Git mob followed by initials will reset to those selected authors. 

I don't think this feature is needed as you could workaround with cmd history and remove the initials from the command. 

Let me know if you still believe there is good value in adding this feature.

**Comment by niksumeiko** [comment]
Hi @rkotze, this demands re-typing all initials of the co-authors that continue in the mob. It might be fine when multiple co-authors leave the mob. In my experience, more often, people drop the mob one by one. Therefore, `git mob -jd` would be a simplifier, a shortcut.

Because with retyping, too many keystrokes are involved:

1. Retype all of the co-authors that continue in the mob:
```bash
g mob jd ak ab hr ur
```

2. Use bash history:
  - Retrieve previously typed line from bash history (`↑` keyup on Mac)  
  _It might require multiple hits if there's something in between)_
  - Move cursor left to delete some initials (many keystrokes)

Yes, these workarounds are there, but `g mob -jd` would certainly be a shorthand.

**Comment by rkotze** [comment]
Hi

I think I'm fine with the idea of removing a co-author but looking at the cli parser rules the approach of -jd would not work as that would result in `{j:d}`. It would need to be something like `--sub=jd`.

**Comment by niksumeiko** [comment]
The `minimist` won't do it, but native arguments parsing has no issue here:

```ts
// $ git mob ab -yz

console.log(process.argv.slice(2));
// ['ab', '-yz']
```


For instance, here's how we can detect removable:
```ts
// $ git mob ab -yz

const authorList = await getAllAuthors();
const authorsToRemove = process.argv.slice(2).reduce((result, a) => {
  if (!a.startsWith('-')) {
     return result;
  }

  const initials = a.substring(1);
  const author = authorList.find(({ key }) => key === initials);

  if (!author) {
    return result;
  }

  return [...result, author];
}, []);

console.log(authorList);
// [Author{ key: 'yz', name… }]
```

**Comment by rkotze** [comment]
I appreciate the suggestion but I think it does need to follow the parser convention because it will result in having an inconsistent way of interpreting the cli flags.

An issue I see is if a co-author key starts with "l" like `-la`. This would trigger the function to list all co-authors. This will apply to all the other short hand flags.

I don't think it's worth complicating the logic of parsing flags so save on key strokes.
