### ISSUE TITLE
Distributed git-mob suggest-coauthors does not have proper line endings on osx

### ISSUE THREAD

**Issue by DavidIAm** [rkotze/git-mob#58]
### Prerequisites

- [X] [Checked that your issue isn't already filed][git-mob issues]
- [X] Tried upgrading to the latest git-mob version (`npm i -g git-mob`)
- [X] Tried upgrading to the latest git version (`brew upgrade git` if installed with Homebrew/Linuxbrew)

### Description

the bin directory has suggest-coauthors file with windows line ending on the shebang line even though I installed it on a mac

### Steps to Reproduce

1. yarn global add git-mob
2. git-mob suggest-coauthors

**Expected behavior:** [What you expect to happen]
List of suggested coauthors

**Actual behavior:** [What actually happens]
env: node\r: No such file or directory

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time... until I edit the file to remove the spurious cr

### Versions

- operating system and version:
macos catalina 10.15.6
- git-mob version (`git-mob --version`):
1.1.0
- git version (`git --version`):
2.27.0

**Comment by rkotze** [comment]
Looks like Yarn has stopped supporting the installation of global packages from version 2. I think this is no longer a relevant issue and will close.

I think it best to install using NPM.
