### ISSUE TITLE
Global mob

### ISSUE THREAD

**Issue by dideler** [rkotze/git-mob#6]
Currently, mobs are set local per project. Users may want to have a mob set globally, where the mob stays the same as you switch between git repos.

**Comment by DennisBecker** [comment]
This would help me a lot as we often work on multiple projects like frontend applications and backend services at the same time.

**Comment by DennisBecker** [comment]
I would not need a switch.

Just today I did pair programming and tried git mob and that was a usual day where we were working on two different repositories.

**Comment by DennisBecker** [comment]
I have switched to git-team now ...

**Comment by rkotze** [comment]
Delivered in v2.1.0.
