### ISSUE TITLE
Create gitmessage file specific to git-mob

### ISSUE THREAD

**Issue by dideler** [rkotze/git-mob#7]
Consider having git-mob use a unique gitmessage file rather than the standard filename `gitmessage`. When creating the file, it copies over the contents of the `gitmessage` file if present, then appends the co-authors.

Reduces risk, as we can safely delete git-mob's file when soloing. Otherwise it's not clear to git-mob if the file was created by itself or the user.

**Comment by rkotze** [comment]
Will add or remove co-author trailers from the git message file.
