### ISSUE TITLE
git mob and git mob-print commands are not found

### ISSUE THREAD

**Issue by ryanjwessel** [rkotze/git-mob#70]
### Prerequisites

- [x] [Checked that your issue isn't already filed][git-mob issues]
- [x] Tried upgrading to the latest git-mob version (`npm i -g git-mob`)
- [x] Tried upgrading to the latest git version (`brew upgrade git` if installed with Homebrew/Linuxbrew)

[git-mob issues]: https://github.com/findmypast-oss/git-mob/issues?utf8=%E2%9C%93&q=is%3Aissue

### Description

I followed the instructions in the README, but when I try to execute `git mob` or `git mob-print`, I receive this response:

`git: 'mob-print' is not a git command. See 'git --help'.`

### Steps to Reproduce

See description

**Expected behavior:** For these git commands to work after installing this library

**Actual behavior:** The git commands provided by this library do not work

**Reproduces how often:** 100%

### Versions

- operating system and version: macOS 11.5.2
- git-mob version (`git-mob --version`): 2.0.0
- git version (`git --version`): 2.32.0

**Comment by rkotze** [comment]
Hi @ryanjwessel 

Can you share your Node and NPM versions, please?

If you're using a Node version manager make sure you have installed under the same version as your project.

Thanks.

**Comment by rkotze** [comment]
No response from user.
